VCO updates

diff --git a/mag/Makefile b/mag/Makefile
--- a/mag/Makefile
+++ b/mag/Makefile
@@ -59,6 +59,37 @@ lvs: lvs.report
 	    exit 1; \
     fi
 
+lvs2.report: $(PROJECT_NAME).lvs.spice
+	netgen -batch eval "set project $(PROJECT_NAME) ; source tcl/lvs_netgen2.tcl"
+
+lvs2: lvs2.report
+	@propOk=1; match=0; port=1; \
+    if grep -q "match uniquely" lvs2.report; then \
+        match=1; \
+    fi; \
+    if grep -q "Property errors were found" lvs2.report; then \
+        propOk=0; \
+    fi; \
+    if grep -q "failed pin matching" lvs2.report; then \
+        match=0; \
+    fi; \
+    if grep -q "Final result: Netlists do not match" lvs2.report; then \
+        match=0; \
+    fi; \
+    if grep -q "port errors" lvs2.report; then \
+        port=0; \
+    fi; \
+    if grep -q "Final result: Circuits match uniquely\." lvs2.report; then \
+        match=1; \
+    fi; \
+	if [ $$match -eq 1 ] && [ $$propOk -eq 1 ] && [ $$port -eq 1 ]; then \
+        echo "LVS OK"; \
+	    exit 0; \
+    else \
+        echo "LVS FAIL: match=$$match properties=$$propOk port=$$port"; \
+	    exit 1; \
+    fi
+
 update_gds:
 	mkdir -p ../gds ../lef
 	magic -noconsole -dnull tcl/update_gds_lef.tcl $(PROJECT_NAME)
